services:

  postgresql:
    image: postgresql
    container_name: postgresql
    build:
      context: ./postgreSQL
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 5s

  transcendence:
    image:  transcendence
    container_name: transcendence
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    restart:  always
    depends_on:
      postgresql:
        condition: service_healthy

networks:
  mynetwork:
    driver: bridge
    name: mynetwork